server.port=8080
spring.application.name=customer-management-api

spring.flyway.enabled=true

# Database Connection Settings
spring.datasource.url=jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS customer_management
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable H2 Web Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Enable percentile calculations for HTTP server requests
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.distribution.percentiles.http.server.requests=0.5,0.9,0.99
management.metrics.distribution.percentiles-histogram.http.server.requests=true

bucket.capacity=50
bucket.refill.tokens=10
bucket.refill.duration.minutes=1
